
export type Property = {
  id: string;
  title: string;
  type: 'Rumah' | 'Apartemen' | 'Tanah';
  location: string;
  price: number;
  beds: number;
  baths: number;
  area: number; // in square meters
  images: string[];
  description: string;
  features: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
};

export const properties: Property[] = [
  {
    id: '1',
    title: 'Vila Modern di Canggu',
    type: 'Rumah',
    location: 'Canggu, Bali',
    price: 5500000000,
    beds: 4,
    baths: 4,
    area: 300,
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/400x300.png',
      'https://placehold.co/400x300.png',
    ],
    description: 'Vila modern menakjubkan dengan kolam renang pribadi dan pemandangan sawah. Terletak di jantung Canggu, dekat dengan pantai dan kafe trendi.',
    features: ['Kolam Renang Pribadi', 'Pemandangan Sawah', 'Dapur Lengkap', 'Parkir Pribadi'],
    coordinates: { lat: 40.730610, lng: -73.935242 },
  },
  {
    id: '2',
    title: 'Apartemen Mewah di SCBD',
    type: 'Apartemen',
    location: 'SCBD, Jakarta Selatan',
    price: 8000000000,
    beds: 3,
    baths: 2,
    area: 150,
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/400x300.png',
    ],
    description: 'Apartemen mewah di lokasi utama dengan akses mudah ke pusat bisnis dan perbelanjaan. Nikmati fasilitas kelas dunia dan pemandangan kota yang spektakuler.',
    features: ['Pemandangan Kota', 'Gym & Kolam Renang', 'Akses Langsung ke Mall', 'Keamanan 24 Jam'],
    coordinates: { lat: 40.748817, lng: -73.985428 },
  },
  {
    id: '3',
    title: 'Rumah Keluarga Nyaman di BSD',
    type: 'Rumah',
    location: 'BSD City, Tangerang',
    price: 2800000000,
    beds: 3,
    baths: 3,
    area: 180,
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/400x300.png',
      'https://placehold.co/400x300.png',
    ],
    description: 'Rumah yang ideal untuk keluarga di lingkungan yang aman dan hijau. Dekat dengan sekolah internasional, rumah sakit, dan pusat perbelanjaan.',
    features: ['Taman Belakang', 'Komplek dengan Keamanan', 'Bebas Banjir', 'Dekat Fasilitas Umum'],
    coordinates: { lat: 40.7182, lng: -73.9984 },
  },
  {
    id: '4',
    title: 'Tanah Strategis di Tepi Pantai Lombok',
    type: 'Tanah',
    location: 'Kuta, Lombok',
    price: 15000000000,
    beds: 0,
    baths: 0,
    area: 5000,
    images: [
      'https://placehold.co/800x600.png',
    ],
    description: 'Sebidang tanah luas di tepi pantai yang indah di Kuta, Lombok. Sempurna untuk pembangunan resor atau vila pribadi. Potensi investasi yang luar biasa.',
    features: ['Lokasi Tepi Pantai', 'Akses Jalan Utama', 'Potensi Investasi Tinggi', 'Zona Pariwisata'],
    coordinates: { lat: 40.705, lng: -74.009 },
  },
  {
    id: '5',
    title: 'Apartemen Studio di Surabaya Pusat',
    type: 'Apartemen',
    location: 'Pusat Kota, Surabaya',
    price: 750000000,
    beds: 1,
    baths: 1,
    area: 35,
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/400x300.png',
    ],
    description: 'Apartemen studio modern dan ringkas di jantung kota Surabaya. Dilengkapi perabotan lengkap, siap huni. Cocok untuk profesional muda atau investasi sewa.',
    features: ['Perabotan Lengkap', 'Lokasi Pusat', 'Fasilitas Gedung', 'Nilai Sewa Baik'],
    coordinates: { lat: 40.75, lng: -73.97 },
  },
  {
    id: '6',
    title: 'Rumah Klasik di Menteng',
    type: 'Rumah',
    location: 'Menteng, Jakarta Pusat',
    price: 25000000000,
    beds: 5,
    baths: 4,
    area: 600,
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/400x300.png',
      'https://placehold.co/400x300.png',
    ],
    description: 'Rumah klasik yang megah di kawasan elit Menteng. Arsitektur kolonial yang terawat baik dengan halaman yang luas. Properti langka dan bergengsi.',
    features: ['Arsitektur Kolonial', 'Halaman Luas', 'Lokasi Prestisius', 'Garasi 4 Mobil'],
    coordinates: { lat: 40.73, lng: -74.05 },
  },
  // Batam Data Starts Here
  {
    id: '7',
    title: 'Rumah Modern di Batam Center',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1800000000,
    beds: 3,
    baths: 2,
    area: 120,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah baru di lokasi strategis Batam Center, dekat dengan terminal feri internasional dan pusat perbelanjaan.',
    features: ['Dekat Mega Mall', 'One Gate System', 'Desain Minimalis', 'Bebas Banjir'],
    coordinates: { lat: 40.69, lng: -74.04 },
  },
  {
    id: '8',
    title: 'Apartemen Pemandangan Laut di Nagoya',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 950000000,
    beds: 2,
    baths: 1,
    area: 60,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen dengan pemandangan laut yang menakjubkan, terletak di pusat hiburan dan kuliner Nagoya.',
    features: ['Sea View', 'Infinity Pool', 'Pusat Kuliner', 'Dekat Nagoya Hill Mall'],
    coordinates: { lat: 40.76, lng: -73.98 },
  },
  {
    id: '9',
    title: 'Tanah Kavling di Nongsa',
    type: 'Tanah',
    location: 'Nongsa, Batam',
    price: 5000000000,
    beds: 0,
    baths: 0,
    area: 2500,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah kavling luas di area resor Nongsa, cocok untuk dibangun vila pribadi atau investasi.',
    features: ['Dekat Lapangan Golf', 'Area Resor', 'Pemandangan Hijau', 'Akses Mudah'],
    coordinates: { lat: 40.77, lng: -73.96 },
  },
  {
    id: '10',
    title: 'Rumah Hook di Sukajadi',
    type: 'Rumah',
    location: 'Sukajadi, Batam',
    price: 2500000000,
    beds: 4,
    baths: 3,
    area: 200,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah posisi hook dengan taman samping yang luas di perumahan elit Sukajadi.',
    features: ['Posisi Hook', 'Taman Luas', 'Clubhouse', 'Keamanan 24 Jam'],
    coordinates: { lat: 40.72, lng: -74.03 },
  },
  {
    id: '11',
    title: 'Ruko 3 Lantai di Baloi',
    type: 'Rumah',
    location: 'Baloi, Batam',
    price: 3200000000,
    beds: 5,
    baths: 3,
    area: 250,
    images: ['https://placehold.co/800x600.png'],
    description: 'Ruko 3 lantai di jalan utama Baloi, cocok untuk usaha dan tempat tinggal.',
    features: ['Lokasi Usaha', 'Jalan Utama', 'Area Parkir', '3 Lantai'],
    coordinates: { lat: 40.73, lng: -73.99 },
  },
  {
    id: '12',
    title: 'Apartemen Tipe Studio di Batam Center',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 550000000,
    beds: 1,
    baths: 1,
    area: 30,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen studio fully furnished, tinggal bawa koper. Berada di tower dengan fasilitas lengkap.',
    features: ['Fully Furnished', 'Siap Huni', 'Sky Garden', 'Dekat Universitas'],
    coordinates: { lat: 40.74, lng: -73.95 },
  },
  {
    id: '13',
    title: 'Rumah di Tiban',
    type: 'Rumah',
    location: 'Tiban, Batam',
    price: 850000000,
    beds: 2,
    baths: 1,
    area: 90,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah terawat di kawasan pemukiman yang tenang dan berkembang di Tiban.',
    features: ['Harga Terjangkau', 'Lingkungan Tenang', 'Dekat Pasar', 'Renovasi Minor'],
    coordinates: { lat: 40.71, lng: -74.02 },
  },
  {
    id: '14',
    title: 'Tanah Industri di Batu Ampar',
    type: 'Tanah',
    location: 'Batu Ampar, Batam',
    price: 25000000000,
    beds: 0,
    baths: 0,
    area: 10000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Lahan industri siap bangun di kawasan pelabuhan Batu Ampar, sangat strategis untuk gudang atau pabrik.',
    features: ['Zona Industri', 'Dekat Pelabuhan', 'Akses Kontainer', 'Investasi Jangka Panjang'],
    coordinates: { lat: 40.7, lng: -74.01 },
  },
  {
    id: '15',
    title: 'Rumah Cluster di Marina City',
    type: 'Rumah',
    location: 'Marina City, Batam',
    price: 1200000000,
    beds: 3,
    baths: 2,
    area: 110,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah dalam cluster baru di Marina City, dekat dengan tempat wisata dan terminal feri Waterfront.',
    features: ['Dekat Tempat Wisata', 'Cluster Baru', 'Fasum Lengkap', 'Dekat Feri ke Singapura'],
    coordinates: { lat: 40.68, lng: -74.03 },
  },
  {
    id: '16',
    title: 'Penthouse Mewah di Harbour Bay',
    type: 'Apartemen',
    location: 'Harbour Bay, Batam',
    price: 12000000000,
    beds: 4,
    baths: 5,
    area: 350,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Penthouse eksklusif dengan private lift dan pemandangan 360 derajat ke laut dan kota Batam.',
    features: ['Private Lift', 'Pemandangan 360 Derajat', 'Rooftop Garden', 'Interior Mewah'],
    coordinates: { lat: 40.765, lng: -73.99 },
  },
  {
    id: '17',
    title: 'Rumah Sederhana di Batu Aji',
    type: 'Rumah',
    location: 'Batu Aji, Batam',
    price: 450000000,
    beds: 2,
    baths: 1,
    area: 72,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah sederhana di kawasan padat penduduk Batu Aji, cocok untuk keluarga kecil.',
    features: ['Murah', 'Padat Penduduk', 'Dekat Sekolah', 'Sudah Renovasi Dapur'],
    coordinates: { lat: 40.695, lng: -74.05 },
  },
  {
    id: '18',
    title: 'Kavling Siap Bangun di Palm Springs',
    type: 'Tanah',
    location: 'Palm Springs, Batam',
    price: 3000000000,
    beds: 0,
    baths: 0,
    area: 500,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah kavling di dalam perumahan mewah Palm Springs Golf & Country Club.',
    features: ['Dalam Komplek Golf', 'Lingkungan Elit', 'Siap Bangun', 'View Lapangan Golf'],
    coordinates: { lat: 40.775, lng: -73.95 },
  },
  {
    id: '19',
    title: 'Rumah Townhouse di Anggrek Mas',
    type: 'Rumah',
    location: 'Anggrek Mas, Batam',
    price: 1500000000,
    beds: 3,
    baths: 3,
    area: 130,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Townhouse modern 3 lantai di perumahan Anggrek Mas, dekat dengan pasar dan sekolah.',
    features: ['3 Lantai', 'Desain Modern', 'Lokasi Sentral', 'Fasilitas Kolam Renang'],
    coordinates: { lat: 40.725, lng: -74.035 },
  },
  {
    id: '20',
    title: 'Apartemen 2BR di Pollux Habibie',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 1200000000,
    beds: 2,
    baths: 1,
    area: 50,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen 2 kamar tidur di icon terbaru Batam, Meisterstadt. Fasilitas super lengkap.',
    features: ['Gedung Tertinggi di Batam', 'Mall di Bawah', 'Bioskop', 'Office Tower'],
    coordinates: { lat: 40.735, lng: -73.985 },
  },
  {
    id: '21',
    title: 'Rumah dengan Kolam Renang di Sekupang',
    type: 'Rumah',
    location: 'Sekupang, Batam',
    price: 3500000000,
    beds: 4,
    baths: 4,
    area: 300,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah luas dengan kolam renang pribadi di kawasan yang asri dan tenang di Sekupang.',
    features: ['Kolam Renang Pribadi', 'Halaman Belakang Luas', 'Lingkungan Asri', 'Dekat Terminal Feri Sekupang'],
    coordinates: { lat: 40.745, lng: -73.965 },
  },
  {
    id: '22',
    title: 'Tanah Kebun di Tembesi',
    type: 'Tanah',
    location: 'Tembesi, Batam',
    price: 800000000,
    beds: 0,
    baths: 0,
    area: 5000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah kebun produktif dengan berbagai tanaman buah, cocok untuk agrowisata atau investasi.',
    features: ['Sudah ada Tanaman', 'Sumber Air', 'Akses Jalan', 'Potensi Agrowisata'],
    coordinates: { lat: 40.715, lng: -74.025 },
  },
  {
    id: '23',
    title: 'Apartemen Compact di One Residence',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 880000000,
    beds: 1,
    baths: 1,
    area: 40,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen modern di atas One Batam Mall dengan akses langsung ke pusat perbelanjaan dan Feri Terminal.',
    features: ['Direct Access to Mall', 'Smart Home System', 'Infinity Pool', 'Lokasi Premium'],
    coordinates: { lat: 40.705, lng: -74.015 },
  },
  {
    id: '24',
    title: 'Rumah Klasik di Taman Duta Mas',
    type: 'Rumah',
    location: 'Duta Mas, Batam',
    price: 2200000000,
    beds: 5,
    baths: 3,
    area: 250,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah besar dengan desain klasik di salah satu perumahan pertama dan ternama di Batam.',
    features: ['Lokasi Matang', 'Jalan Lebar', 'Lingkungan Aman', 'Dekat Pasar Penuin'],
    coordinates: { lat: 40.685, lng: -74.035 },
  },
  {
    id: '25',
    title: 'Villa di Turi Beach Resort',
    type: 'Rumah',
    location: 'Nongsa, Batam',
    price: 6000000000,
    beds: 3,
    baths: 3,
    area: 280,
    images: ['https://placehold.co/800x600.png'],
    description: 'Villa pribadi di dalam kawasan Turi Beach Resort, nikmati fasilitas hotel bintang 5.',
    features: ['Dalam Kawasan Resor', 'Pemandangan Pantai', 'Akses Fasilitas Hotel', 'Privasi Terjamin'],
    coordinates: { lat: 40.768, lng: -73.988 },
  },
  {
    id: '26',
    title: 'Tanah Komersial di Simpang Kabil',
    type: 'Tanah',
    location: 'Simpang Kabil, Batam',
    price: 15000000000,
    beds: 0,
    baths: 0,
    area: 3000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah di persimpangan jalan utama, sangat cocok untuk dibangun pusat komersial atau perkantoran.',
    features: ['Lokasi Sudut', 'Jalan Utama', 'Zona Komersial', 'Traffic Tinggi'],
    coordinates: { lat: 40.698, lng: -74.048 },
  },
  {
    id: '27',
    title: 'Rumah Type 36 di Sagulung',
    type: 'Rumah',
    location: 'Sagulung, Batam',
    price: 350000000,
    beds: 2,
    baths: 1,
    area: 72,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah subsidi terjangkau di daerah Sagulung, investasi pertama yang bagus.',
    features: ['Rumah Subsidi', 'Terjangkau', 'Kawasan Berkembang', 'Dekat Kawasan Industri'],
    coordinates: { lat: 40.778, lng: -73.958 },
  },
  {
    id: '28',
    title: 'Apartemen 3BR di Formosa Residence',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 2500000000,
    beds: 3,
    baths: 2,
    area: 110,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Apartemen luas dengan 3 kamar tidur di jantung Nagoya, terhubung dengan Nagoya Hill Mall.',
    features: ['Terhubung ke Mall', '3 Kamar Tidur', 'Lokasi Prime', 'Kolam Renang Indoor'],
    coordinates: { lat: 40.728, lng: -74.038 },
  },
  {
    id: '29',
    title: 'Rumah di Perumahan Botania Garden',
    type: 'Rumah',
    location: 'Botania, Batam',
    price: 980000000,
    beds: 3,
    baths: 2,
    area: 105,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah di perumahan yang ramai dengan fasilitas lengkap seperti pasar basah dan plaza.',
    features: ['Fasilitas Internal Lengkap', 'Pasar Basah', 'Plaza', 'Dekat Bandara'],
    coordinates: { lat: 40.738, lng: -73.988 },
  },
  {
    id: '30',
    title: 'Tanah Pinggir Jalan di Sei Panas',
    type: 'Tanah',
    location: 'Sei Panas, Batam',
    price: 4000000000,
    beds: 0,
    baths: 0,
    area: 1000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah strategis di pinggir jalan raya Sei Panas, cocok untuk berbagai jenis usaha.',
    features: ['Pinggir Jalan Raya', 'Akses Mudah', 'Dekat Pusat Kota', 'Bentuk Tanah Kotak'],
    coordinates: { lat: 40.748, lng: -73.958 },
  },
  {
    id: '31',
    title: 'Rumah Mewah di Beverly Hills',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 7000000000,
    beds: 5,
    baths: 5,
    area: 450,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah mewah di kawasan perumahan paling elit di Batam, Beverly Hills. Keamanan dan privasi terjamin.',
    features: ['Kawasan Elit', 'Keamanan Super Ketat', 'Clubhouse Pribadi', 'Desain Megah'],
    coordinates: { lat: 40.718, lng: -74.028 },
  },
  {
    id: '32',
    title: 'Apartemen Loft di Citra Plaza',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 1600000000,
    beds: 2,
    baths: 2,
    area: 80,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen tipe loft dengan langit-langit tinggi, memberikan kesan luas dan mewah.',
    features: ['Tipe Loft', 'Langit-langit Tinggi', 'Desain Unik', 'Lokasi Pusat'],
    coordinates: { lat: 40.708, lng: -74.018 },
  },
  {
    id: '33',
    title: 'Tanah di Pulau Galang',
    type: 'Tanah',
    location: 'Pulau Galang, Batam',
    price: 2000000000,
    beds: 0,
    baths: 0,
    area: 15000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah luas di Pulau Galang, dekat dengan Jembatan Barelang. Potensi untuk pariwisata.',
    features: ['Dekat Jembatan Barelang', 'Pemandangan Laut', 'Udara Segar', 'Investasi Masa Depan'],
    coordinates: { lat: 40.688, lng: -74.038 },
  },
  {
    id: '34',
    title: 'Rumah Minimalis di Legenda Malaka',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1300000000,
    beds: 3,
    baths: 2,
    area: 110,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah dengan desain minimalis modern di perumahan Legenda Malaka yang strategis.',
    features: ['Desain Minimalis', 'Lokasi Strategis', 'Dekat Sekolah', 'Lingkungan Rapi'],
    coordinates: { lat: 40.762, lng: -73.982 },
  },
  {
    id: '35',
    title: 'Apartemen 1BR di BCS Mall',
    type: 'Apartemen',
    location: 'Baloi, Batam',
    price: 650000000,
    beds: 1,
    baths: 1,
    area: 38,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen yang terintegrasi dengan Batam City Square (BCS) Mall, kemudahan dalam genggaman.',
    features: ['Terintegrasi dengan Mall', 'Akses Mudah', 'Pusat Hiburan', 'Nilai Sewa Tinggi'],
    coordinates: { lat: 40.692, lng: -74.042 },
  },
  {
    id: '36',
    title: 'Rumah Tua Hitung Tanah di Jodoh',
    type: 'Rumah',
    location: 'Jodoh, Batam',
    price: 1500000000,
    beds: 4,
    baths: 2,
    area: 300,
    images: ['https://placehold.co/800x600.png'],
    description: 'Dijual rumah tua hitung harga tanah saja di kawasan bisnis Jodoh yang ramai.',
    features: ['Hitung Tanah', 'Lokasi Bisnis', 'Dekat Pelabuhan', 'Investasi Properti'],
    coordinates: { lat: 40.772, lng: -73.952 },
  },
  {
    id: '37',
    title: 'Tanah Kavling di Perumahan KDA',
    type: 'Tanah',
    location: 'Batam Center, Batam',
    price: 900000000,
    beds: 0,
    baths: 0,
    area: 200,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah kavling siap bangun di dalam perumahan KDA yang asri dan tenang.',
    features: ['Siap Bangun', 'Dalam Perumahan', 'Lingkungan Tenang', 'Jalan Sudah Aspal'],
    coordinates: { lat: 40.722, lng: -74.032 },
  },
  {
    id: '38',
    title: 'Rumah di Orchard Park',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 4500000000,
    beds: 4,
    baths: 4,
    area: 280,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Rumah mewah di cluster premium Orchard Park by Agung Podomoro Land. Fasilitas bintang lima.',
    features: ['Pengembang Terkenal', 'Clubhouse Mewah', 'One-Stop Living', 'Investasi Terbaik'],
    coordinates: { lat: 40.732, lng: -73.982 },
  },
  {
    id: '39',
    title: 'Apartemen Studio Murah di Nagoya',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 480000000,
    beds: 1,
    baths: 1,
    area: 25,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen studio dengan harga terjangkau di area Nagoya, cocok untuk investasi sewa harian.',
    features: ['Harga Terjangkau', 'Potensi Sewa Harian', 'Pusat Kota', 'Cocok untuk AirBnB'],
    coordinates: { lat: 40.742, lng: -73.962 },
  },
  {
    id: '40',
    title: 'Villa Pinggir Pantai di Nongsa',
    type: 'Rumah',
    location: 'Nongsa, Batam',
    price: 8500000000,
    beds: 5,
    baths: 5,
    area: 600,
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/400x300.png'],
    description: 'Villa pribadi mewah dengan akses langsung ke pantai pribadi di kawasan Nongsa.',
    features: ['Private Beach Access', 'Pemandangan Singapura', 'Kolam Renang Infinity', 'Sangat Pribadi'],
    coordinates: { lat: 40.712, lng: -74.022 },
  },
    {
    id: '41',
    title: 'Rumah Sederhana di Piayu',
    type: 'Rumah',
    location: 'Piayu, Batam',
    price: 400000000,
    beds: 2,
    baths: 1,
    area: 78,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah di kawasan berkembang Piayu, dekat dengan area wisata laut.',
    features: ['Dekat Wisata Pantai', 'Harga Ekonomis', 'Kawasan Berkembang', 'Investasi Awal'],
    coordinates: { lat: 40.702, lng: -74.012 },
  },
  {
    id: '42',
    title: 'Tanah Industri di Kabil',
    type: 'Tanah',
    location: 'Kabil, Batam',
    price: 30000000000,
    beds: 0,
    baths: 0,
    area: 12000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Lahan industri di kawasan terpadu Kabil, cocok untuk industri berat.',
    features: ['Kawasan Industri Terpadu', 'Akses Pelabuhan Kargo', 'Infrastruktur Lengkap', 'Zona Industri Berat'],
    coordinates: { lat: 40.682, lng: -74.032 },
  },
  {
    id: '43',
    title: 'Apartemen di Imperium',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 1800000000,
    beds: 2,
    baths: 2,
    area: 85,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen eksklusif di The Imperium, Batam Center, dengan private lift.',
    features: ['Private Lift', 'Unit Terbatas', 'Pemandangan Kota', 'Dekat Kantor Pemerintahan'],
    coordinates: { lat: 40.764, lng: -73.984 },
  },
  {
    id: '44',
    title: 'Rumah di Perumahan Puri Legenda',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1100000000,
    beds: 3,
    baths: 2,
    area: 98,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah di lokasi yang sangat strategis, Puri Legenda, dekat sekolah dan pasar.',
    features: ['Sangat Strategis', 'Dekat Sekolah Mondial', 'Pasar Puri Legenda', 'Akses Mudah'],
    coordinates: { lat: 40.694, lng: -74.044 },
  },
  {
    id: '45',
    title: 'Tanah Matang di Bengkong',
    type: 'Tanah',
    location: 'Bengkong, Batam',
    price: 2000000000,
    beds: 0,
    baths: 0,
    area: 500,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah matang siap bangun di kawasan padat penduduk Bengkong.',
    features: ['Tanah Matang', 'Padat Penduduk', 'Cocok untuk Kos-kosan', 'Dekat Golden Prawn'],
    coordinates: { lat: 40.774, lng: -73.954 },
  },
  {
    id: '46',
    title: 'Rumah Hook di Citra Indah',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 2000000000,
    beds: 3,
    baths: 3,
    area: 180,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah hook di perumahan Citra Indah, seberang Mega Mall Batam Center.',
    features: ['Depan Mega Mall', 'Posisi Hook', 'Jalan Kaki ke Feri Terminal', 'Prime Location'],
    coordinates: { lat: 40.724, lng: -74.034 },
  },
  {
    id: '47',
    title: 'Apartemen Tipe Besar di The Hills',
    type: 'Apartemen',
    location: 'Sukajadi, Batam',
    price: 3800000000,
    beds: 3,
    baths: 3,
    area: 160,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen tipe besar dengan pemandangan lapangan golf di The Hills, Sukajadi.',
    features: ['View Lapangan Golf', 'Unit Luas', 'Kawasan Elit', 'Udara Segar'],
    coordinates: { lat: 40.734, lng: -73.984 },
  },
  {
    id: '48',
    title: 'Tanah Pinggir Pantai di Batu Besar',
    type: 'Tanah',
    location: 'Batu Besar, Batam',
    price: 7000000000,
    beds: 0,
    baths: 0,
    area: 8000,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah pinggir pantai di area Batu Besar, dekat bandara. Cocok untuk resort atau restoran seafood.',
    features: ['Pinggir Pantai', 'Dekat Bandara', 'Pemandangan Indah', 'Zona Pariwisata'],
    coordinates: { lat: 40.744, lng: -73.964 },
  },
  {
    id: '49',
    title: 'Rumah di Perumahan Cendana',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1700000000,
    beds: 3,
    baths: 2,
    area: 140,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah terawat di Perumahan Cendana, salah satu perumahan favorit di Batam Center.',
    features: ['Lokasi Favorit', 'One Gate System', 'Lingkungan Aman', 'Dekat Sekolah Yos Sudarso'],
    coordinates: { lat: 40.714, lng: -74.024 },
  },
  {
    id: '50',
    title: 'Ruko di Komplek Windsor',
    type: 'Rumah',
    location: 'Nagoya, Batam',
    price: 2800000000,
    beds: 4,
    baths: 3,
    area: 200,
    images: ['https://placehold.co/800x600.png'],
    description: 'Ruko di komplek Windsor yang ramai, pusat perdagangan dan perkantoran di Nagoya.',
    features: ['Pusat Perdagangan', 'Kawasan Ramai', 'Cocok untuk Kantor', 'Investasi Menarik'],
    coordinates: { lat: 40.704, lng: -74.014 },
  },
  {
    id: '51',
    title: 'Apartemen di The Summer',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 700000000,
    beds: 1,
    baths: 1,
    area: 35,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen kompak dengan fasilitas lengkap, dekat dengan Pasar Pasir Putih.',
    features: ['Fasilitas Lengkap', 'Dekat Pasar', 'Harga Kompetitif', 'Cocok untuk Pasangan Muda'],
    coordinates: { lat: 40.684, lng: -74.034 },
  },
  {
    id: '52',
    title: 'Rumah di Plamo Garden',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1400000000,
    beds: 3,
    baths: 2,
    area: 118,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah di Plamo Garden, perumahan dengan danau buatan dan lingkungan yang hijau.',
    features: ['Ada Danau Buatan', 'Lingkungan Hijau', 'Dekat Pollux Habibie', 'Row Jalan Lebar'],
    coordinates: { lat: 40.766, lng: -73.986 },
  },
  {
    id: '53',
    title: 'Tanah Kavling di Duriangkang',
    type: 'Tanah',
    location: 'Duriangkang, Batam',
    price: 500000000,
    beds: 0,
    baths: 0,
    area: 300,
    images: ['https://placehold.co/800x600.png'],
    description: 'Tanah kavling di area yang sedang berkembang pesat di Duriangkang.',
    features: ['Area Berkembang', 'Investasi Tanah', 'Harga Masih Murah', 'Dekat Waduk Duriangkang'],
    coordinates: { lat: 40.696, lng: -74.046 },
  },
  {
    id: '54',
    title: 'Rumah Tua di Baloi',
    type: 'Rumah',
    location: 'Baloi, Batam',
    price: 1000000000,
    beds: 3,
    baths: 1,
    area: 200,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah tua di kawasan Baloi yang sangat strategis, butuh renovasi total atau bangun ulang.',
    features: ['Lokasi Strategis Baloi', 'Hitung Tanah', 'Potensi Bangun Ulang', 'Dekat BCS Mall'],
    coordinates: { lat: 40.776, lng: -73.956 },
  },
  {
    id: '55',
    title: 'Apartemen Mewah di Aston',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 2200000000,
    beds: 2,
    baths: 2,
    area: 90,
    images: ['https://placehold.co/800x600.png'],
    description: 'Apartemen mewah yang menyatu dengan Hotel Aston Nagoya, nikmati fasilitas hotel.',
    features: ['Menyatu dengan Hotel', 'Fasilitas Hotel', 'Disewakan Mudah', 'Lokasi Pusat Nagoya'],
    coordinates: { lat: 40.726, lng: -74.036 },
  },
  {
    id: '56',
    title: 'Rumah Cluster di Taman Raya',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 900000000,
    beds: 2,
    baths: 2,
    area: 90,
    images: ['https://placehold.co/800x600.png'],
    description: 'Rumah di perumahan besar Taman Raya, fasilitas sangat lengkap di dalam perumahan.',
    features: ['Perumahan Besar', 'Fasum Lengkap', 'Dekat Plaza Botania', 'Banyak Pilihan Kuliner'],
    coordinates: { lat: 40.736, lng: -73.986 },
  },
];
