
export type Property = {
  id: string;
  title: string;
  type: 'Rumah' | 'Apartemen' | 'Tanah Kosong' | 'Gudang' | 'Ruko' | 'Galangan Kapal' | 'Pabrik';
  location: string;
  price: number;
  beds: number;
  baths: number;
  buildingArea: number; // in square meters
  landArea: number; // in square meters
  images: string[];
  description: string;
  features: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
};

const RUMAH_IMAGES = [
  'https://www.emporioarchitect.com/img/blog/ide-desain-rumah-mewah-untuk-anda-130125013838148646.jpg', 
  'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg',
  'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg',
];
const APARTEMEN_IMAGES = [
  'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg', 
  'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg',
  'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg',
];
const GUDANG_IMAGES = [
  'https://images.unsplash.com/photo-1587135304383-a369947c3555?q=80&w=2070&auto=format&fit=crop', 
  'https://images.unsplash.com/photo-1616433369402-49c4886616a9?q=80&w=1932&auto=format&fit=crop',
];
const PABRIK_IMAGES = [
  'https://img.freepik.com/foto-gratis/silo-pertanian-eksterior-bangunan_10180831.jpg',
  'https://images.unsplash.com/photo-1487875961445-47a003a6c167?q=80&w=2070&auto=format&fit=crop',
];
const TANAH_KOSONG_IMAGES = [
  'https://images.unsplash.com/photo-1594704410659-0787888c374b?q=80&w=2069&auto=format&fit=crop', 
  'https://images.unsplash.com/photo-1437719417032-8595fd9e9dc6?q=80&w=1974&auto=format&fit=crop',
];
const RUKO_IMAGES = [
  'https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=2070&auto=format&fit=crop', 
  'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1974&auto=format&fit=crop',
];
const GALANGAN_KAPAL_IMAGES = [
  'https://images.unsplash.com/photo-1541692354854-15f5a894a8f9?q=80&w=2070&auto=format&fit=crop', 
  'https://images.unsplash.com/photo-1611315482329-b68a73a39b82?q=80&w=1949&auto=format&fit=crop',
];


export const properties: Property[] = [
  {
    id: '7',
    title: 'Rumah Modern di Batam Center',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1800000000,
    beds: 3,
    baths: 2,
    buildingArea: 120,
    landArea: 150,
    images: RUMAH_IMAGES,
    description: 'Rumah baru di lokasi strategis Batam Center, dekat dengan terminal feri internasional dan pusat perbelanjaan.',
    features: ['Dekat Mega Mall', 'One Gate System', 'Desain Minimalis', 'Bebas Banjir'],
    coordinates: { lat: 1.118, lng: 104.048 },
  },
  {
    id: '8',
    title: 'Apartemen Pemandangan Laut di Nagoya',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 950000000,
    beds: 2,
    baths: 1,
    buildingArea: 60,
    landArea: 60,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen dengan pemandangan laut yang menakjubkan, terletak di pusat hiburan dan kuliner Nagoya.',
    features: ['Sea View', 'Infinity Pool', 'Pusat Kuliner', 'Dekat Nagoya Hill Mall'],
    coordinates: { lat: 1.141, lng: 104.01 },
  },
  {
    id: '9',
    title: 'Tanah Kavling di Nongsa',
    type: 'Tanah Kosong',
    location: 'Nongsa, Batam',
    price: 5000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 2500,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah kavling luas di area resor Nongsa, cocok untuk dibangun vila pribadi atau investasi.',
    features: ['Dekat Lapangan Golf', 'Area Resor', 'Pemandangan Hijau', 'Akses Mudah'],
    coordinates: { lat: 1.18, lng: 104.09 },
  },
  {
    id: '10',
    title: 'Rumah Hook di Sukajadi',
    type: 'Rumah',
    location: 'Sukajadi, Batam',
    price: 2500000000,
    beds: 4,
    baths: 3,
    buildingArea: 200,
    landArea: 240,
    images: RUMAH_IMAGES,
    description: 'Rumah posisi hook dengan taman samping yang luas di perumahan elit Sukajadi.',
    features: ['Posisi Hook', 'Taman Luas', 'Clubhouse', 'Keamanan 24 Jam'],
    coordinates: { lat: 1.13, lng: 104.045 },
  },
  {
    id: '11',
    title: 'Ruko 3 Lantai di Baloi',
    type: 'Ruko',
    location: 'Baloi, Batam',
    price: 3200000000,
    beds: 0,
    baths: 3,
    buildingArea: 250,
    landArea: 100,
    images: RUKO_IMAGES,
    description: 'Ruko 3 lantai di jalan utama Baloi, cocok untuk usaha dan tempat tinggal.',
    features: ['Lokasi Usaha', 'Jalan Utama', 'Area Parkir', '3 Lantai'],
    coordinates: { lat: 1.134, lng: 104.022 },
  },
  {
    id: '12',
    title: 'Apartemen Tipe Studio di Batam Center',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 550000000,
    beds: 1,
    baths: 1,
    buildingArea: 30,
    landArea: 30,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen studio fully furnished, tinggal bawa koper. Berada di tower dengan fasilitas lengkap.',
    features: ['Fully Furnished', 'Siap Huni', 'Sky Garden', 'Dekat Universitas'],
    coordinates: { lat: 1.124, lng: 104.051 },
  },
  {
    id: '13',
    title: 'Gudang di Tiban',
    type: 'Gudang',
    location: 'Tiban, Batam',
    price: 850000000,
    beds: 0,
    baths: 1,
    buildingArea: 900,
    landArea: 1200,
    images: GUDANG_IMAGES,
    description: 'Gudang terawat di kawasan pemukiman yang tenang dan berkembang di Tiban.',
    features: ['Harga Terjangkau', 'Lingkungan Tenang', 'Dekat Pasar', 'Akses Kontainer'],
    coordinates: { lat: 1.11, lng: 103.98 },
  },
  {
    id: '14',
    title: 'Pabrik di Batu Ampar',
    type: 'Pabrik',
    location: 'Batu Ampar, Batam',
    price: 25000000000,
    beds: 0,
    baths: 0,
    buildingArea: 5000,
    landArea: 10000,
    images: PABRIK_IMAGES,
    description: 'Lahan industri siap bangun di kawasan pelabuhan Batu Ampar, sangat strategis untuk gudang atau pabrik.',
    features: ['Zona Industri', 'Dekat Pelabuhan', 'Akses Kontainer', 'Investasi Jangka Panjang'],
    coordinates: { lat: 1.16, lng: 104.01 },
  },
  {
    id: '15',
    title: 'Galangan Kapal di Marina City',
    type: 'Galangan Kapal',
    location: 'Marina City, Batam',
    price: 120000000000,
    beds: 0,
    baths: 0,
    buildingArea: 2000,
    landArea: 11000,
    images: GALANGAN_KAPAL_IMAGES,
    description: 'Galangan kapal di Marina City, dekat dengan tempat wisata dan terminal feri Waterfront.',
    features: ['Dekat Tempat Wisata', 'Akses Laut', 'Fasum Lengkap', 'Dekat Feri ke Singapura'],
    coordinates: { lat: 1.10, lng: 103.93 },
  },
  {
    id: '16',
    title: 'Penthouse Mewah di Harbour Bay',
    type: 'Apartemen',
    location: 'Harbour Bay, Batam',
    price: 12000000000,
    beds: 4,
    baths: 5,
    buildingArea: 350,
    landArea: 350,
    images: APARTEMEN_IMAGES,
    description: 'Penthouse eksklusif dengan private lift dan pemandangan 360 derajat ke laut dan kota Batam.',
    features: ['Private Lift', 'Pemandangan 360 Derajat', 'Rooftop Garden', 'Interior Mewah'],
    coordinates: { lat: 1.155, lng: 104.015 },
  },
  {
    id: '17',
    title: 'Rumah Sederhana di Batu Aji',
    type: 'Rumah',
    location: 'Batu Aji, Batam',
    price: 450000000,
    beds: 2,
    baths: 1,
    buildingArea: 60,
    landArea: 72,
    images: RUMAH_IMAGES,
    description: 'Rumah sederhana di kawasan padat penduduk Batu Aji, cocok untuk keluarga kecil.',
    features: ['Murah', 'Padat Penduduk', 'Dekat Sekolah', 'Sudah Renovasi Dapur'],
    coordinates: { lat: 1.05, lng: 103.96 },
  },
  {
    id: '18',
    title: 'Kavling Siap Bangun di Palm Springs',
    type: 'Tanah Kosong',
    location: 'Palm Springs, Batam',
    price: 3000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 500,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah kavling di dalam perumahan mewah Palm Springs Golf & Country Club.',
    features: ['Dalam Komplek Golf', 'Lingkungan Elit', 'Siap Bangun', 'View Lapangan Golf'],
    coordinates: { lat: 1.14, lng: 104.06 },
  },
  {
    id: '19',
    title: 'Rumah Townhouse di Anggrek Mas',
    type: 'Rumah',
    location: 'Anggrek Mas, Batam',
    price: 1500000000,
    beds: 3,
    baths: 3,
    buildingArea: 130,
    landArea: 90,
    images: RUMAH_IMAGES,
    description: 'Townhouse modern 3 lantai di perumahan Anggrek Mas, dekat dengan pasar dan sekolah.',
    features: ['3 Lantai', 'Desain Modern', 'Lokasi Sentral', 'Fasilitas Kolam Renang'],
    coordinates: { lat: 1.127, lng: 104.037 },
  },
  {
    id: '20',
    title: 'Apartemen 2BR di Pollux Habibie',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 1200000000,
    beds: 2,
    baths: 1,
    buildingArea: 50,
    landArea: 50,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen 2 kamar tidur di icon terbaru Batam, Meisterstadt. Fasilitas super lengkap.',
    features: ['Gedung Tertinggi di Batam', 'Mall di Bawah', 'Bioskop', 'Office Tower'],
    coordinates: { lat: 1.12, lng: 104.04 },
  },
  {
    id: '21',
    title: 'Rumah dengan Kolam Renang di Sekupang',
    type: 'Rumah',
    location: 'Sekupang, Batam',
    price: 3500000000,
    beds: 4,
    baths: 4,
    buildingArea: 300,
    landArea: 400,
    images: RUMAH_IMAGES,
    description: 'Rumah luas dengan kolam renang pribadi di kawasan yang asri dan tenang di Sekupang.',
    features: ['Kolam Renang Pribadi', 'Halaman Belakang Luas', 'Lingkungan Asri', 'Dekat Terminal Feri Sekupang'],
    coordinates: { lat: 1.13, lng: 103.95 },
  },
  {
    id: '22',
    title: 'Tanah Kebun di Tembesi',
    type: 'Tanah Kosong',
    location: 'Tembesi, Batam',
    price: 800000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 5000,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah kebun produktif dengan berbagai tanaman buah, cocok untuk agrowisata atau investasi.',
    features: ['Sudah ada Tanaman', 'Sumber Air', 'Akses Jalan', 'Potensi Agrowisata'],
    coordinates: { lat: 1.03, lng: 103.99 },
  },
  {
    id: '23',
    title: 'Apartemen Compact di One Residence',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 880000000,
    beds: 1,
    baths: 1,
    buildingArea: 40,
    landArea: 40,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen modern di atas One Batam Mall dengan akses langsung ke pusat perbelanjaan dan Feri Terminal.',
    features: ['Direct Access to Mall', 'Smart Home System', 'Infinity Pool', 'Lokasi Premium'],
    coordinates: { lat: 1.119, lng: 104.049 },
  },
  {
    id: '24',
    title: 'Rumah Klasik di Taman Duta Mas',
    type: 'Rumah',
    location: 'Duta Mas, Batam',
    price: 2200000000,
    beds: 5,
    baths: 3,
    buildingArea: 250,
    landArea: 300,
    images: RUMAH_IMAGES,
    description: 'Rumah besar dengan desain klasik di salah satu perumahan pertama dan ternama di Batam.',
    features: ['Lokasi Matang', 'Jalan Lebar', 'Lingkungan Aman', 'Dekat Pasar Penuin'],
    coordinates: { lat: 1.135, lng: 104.028 },
  },
  {
    id: '25',
    title: 'Villa di Turi Beach Resort',
    type: 'Rumah',
    location: 'Nongsa, Batam',
    price: 6000000000,
    beds: 3,
    baths: 3,
    buildingArea: 280,
    landArea: 500,
    images: RUMAH_IMAGES,
    description: 'Villa pribadi di dalam kawasan Turi Beach Resort, nikmati fasilitas hotel bintang 5.',
    features: ['Dalam Kawasan Resor', 'Pemandangan Pantai', 'Akses Fasilitas Hotel', 'Privasi Terjamin'],
    coordinates: { lat: 1.19, lng: 104.1 },
  },
  {
    id: '26',
    title: 'Tanah Komersial di Simpang Kabil',
    type: 'Tanah Kosong',
    location: 'Simpang Kabil, Batam',
    price: 15000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 3000,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah di persimpangan jalan utama, sangat cocok untuk dibangun pusat komersial atau perkantoran.',
    features: ['Lokasi Sudut', 'Jalan Utama', 'Zona Komersial', 'Traffic Tinggi'],
    coordinates: { lat: 1.10, lng: 104.07 },
  },
  {
    id: '27',
    title: 'Rumah Type 36 di Sagulung',
    type: 'Rumah',
    location: 'Sagulung, Batam',
    price: 350000000,
    beds: 2,
    baths: 1,
    buildingArea: 36,
    landArea: 72,
    images: RUMAH_IMAGES,
    description: 'Rumah subsidi terjangkau di daerah Sagulung, investasi pertama yang bagus.',
    features: ['Rumah Subsidi', 'Terjangkau', 'Kawasan Berkembang', 'Dekat Kawasan Industri'],
    coordinates: { lat: 1.02, lng: 103.94 },
  },
  {
    id: '28',
    title: 'Apartemen 3BR di Formosa Residence',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 2500000000,
    beds: 3,
    baths: 2,
    buildingArea: 110,
    landArea: 110,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen luas dengan 3 kamar tidur di jantung Nagoya, terhubung dengan Nagoya Hill Mall.',
    features: ['Terhubung ke Mall', '3 Kamar Tidur', 'Lokasi Prime', 'Kolam Renang Indoor'],
    coordinates: { lat: 1.143, lng: 104.012 },
  },
  {
    id: '29',
    title: 'Rumah di Perumahan Botania Garden',
    type: 'Rumah',
    location: 'Botania, Batam',
    price: 980000000,
    beds: 3,
    baths: 2,
    buildingArea: 80,
    landArea: 105,
    images: RUMAH_IMAGES,
    description: 'Rumah di perumahan yang ramai dengan fasilitas lengkap seperti pasar basah dan plaza.',
    features: ['Fasilitas Internal Lengkap', 'Pasar Basah', 'Plaza', 'Dekat Bandara'],
    coordinates: { lat: 1.11, lng: 104.08 },
  },
  {
    id: '30',
    title: 'Tanah Pinggir Jalan di Sei Panas',
    type: 'Tanah Kosong',
    location: 'Sei Panas, Batam',
    price: 4000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 1000,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah strategis di pinggir jalan raya Sei Panas, cocok untuk berbagai jenis usaha.',
    features: ['Pinggir Jalan Raya', 'Akses Mudah', 'Dekat Pusat Kota', 'Bentuk Tanah Kotak'],
    coordinates: { lat: 1.138, lng: 104.033 },
  },
  {
    id: '31',
    title: 'Rumah Mewah di Beverly Hills',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 7000000000,
    beds: 5,
    baths: 5,
    buildingArea: 450,
    landArea: 500,
    images: RUMAH_IMAGES,
    description: 'Rumah mewah di kawasan perumahan paling elit di Batam, Beverly Hills. Keamanan dan privasi terjamin.',
    features: ['Kawasan Elit', 'Keamanan Super Ketat', 'Clubhouse Pribadi', 'Desain Megah'],
    coordinates: { lat: 1.132, lng: 104.048 },
  },
  {
    id: '32',
    title: 'Apartemen Loft di Citra Plaza',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 1600000000,
    beds: 2,
    baths: 2,
    buildingArea: 80,
    landArea: 80,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen tipe loft dengan langit-langit tinggi, memberikan kesan luas dan mewah.',
    features: ['Tipe Loft', 'Langit-langit Tinggi', 'Desain Unik', 'Lokasi Pusat'],
    coordinates: { lat: 1.14, lng: 104.015 },
  },
  {
    id: '33',
    title: 'Tanah di Pulau Galang',
    type: 'Tanah Kosong',
    location: 'Pulau Galang, Batam',
    price: 2000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 15000,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah luas di Pulau Galang, dekat dengan Jembatan Barelang. Potensi untuk pariwisata.',
    features: ['Dekat Jembatan Barelang', 'Pemandangan Laut', 'Udara Segar', 'Investasi Masa Depan'],
    coordinates: { lat: 0.74, lng: 104.2 },
  },
  {
    id: '34',
    title: 'Rumah Minimalis di Legenda Malaka',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1300000000,
    beds: 3,
    baths: 2,
    buildingArea: 110,
    landArea: 120,
    images: RUMAH_IMAGES,
    description: 'Rumah dengan desain minimalis modern di perumahan Legenda Malaka yang strategis.',
    features: ['Desain Minimalis', 'Lokasi Strategis', 'Dekat Sekolah', 'Lingkungan Rapi'],
    coordinates: { lat: 1.105, lng: 104.055 },
  },
  {
    id: '35',
    title: 'Apartemen 1BR di BCS Mall',
    type: 'Apartemen',
    location: 'Baloi, Batam',
    price: 650000000,
    beds: 1,
    baths: 1,
    buildingArea: 38,
    landArea: 38,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen yang terintegrasi dengan Batam City Square (BCS) Mall, kemudahan dalam genggaman.',
    features: ['Terintegrasi dengan Mall', 'Akses Mudah', 'Pusat Hiburan', 'Nilai Sewa Tinggi'],
    coordinates: { lat: 1.13, lng: 104.018 },
  },
  {
    id: '36',
    title: 'Rumah Tua Hitung Tanah di Jodoh',
    type: 'Rumah',
    location: 'Jodoh, Batam',
    price: 1500000000,
    beds: 4,
    baths: 2,
    buildingArea: 150,
    landArea: 300,
    images: RUMAH_IMAGES,
    description: 'Dijual rumah tua hitung harga tanah saja di kawasan bisnis Jodoh yang ramai.',
    features: ['Hitung Tanah', 'Lokasi Bisnis', 'Dekat Pelabuhan', 'Investasi Properti'],
    coordinates: { lat: 1.15, lng: 104.02 },
  },
  {
    id: '37',
    title: 'Tanah Kavling di Perumahan KDA',
    type: 'Tanah Kosong',
    location: 'Batam Center, Batam',
    price: 900000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 200,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah kavling siap bangun di dalam perumahan KDA yang asri dan tenang.',
    features: ['Siap Bangun', 'Dalam Perumahan', 'Lingkungan Tenang', 'Jalan Sudah Aspal'],
    coordinates: { lat: 1.125, lng: 104.06 },
  },
  {
    id: '38',
    title: 'Rumah di Orchard Park',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 4500000000,
    beds: 4,
    baths: 4,
    buildingArea: 280,
    landArea: 320,
    images: RUMAH_IMAGES,
    description: 'Rumah mewah di cluster premium Orchard Park by Agung Podomoro Land. Fasilitas bintang lima.',
    features: ['Pengembang Terkenal', 'Clubhouse Mewah', 'One-Stop Living', 'Investasi Terbaik'],
    coordinates: { lat: 1.115, lng: 104.058 },
  },
  {
    id: '39',
    title: 'Apartemen Studio Murah di Nagoya',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 480000000,
    beds: 1,
    baths: 1,
    buildingArea: 25,
    landArea: 25,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen studio dengan harga terjangkau di area Nagoya, cocok untuk investasi sewa harian.',
    features: ['Harga Terjangkau', 'Potensi Sewa Harian', 'Pusat Kota', 'Cocok untuk AirBnB'],
    coordinates: { lat: 1.145, lng: 104.018 },
  },
  {
    id: '40',
    title: 'Villa Pinggir Pantai di Nongsa',
    type: 'Rumah',
    location: 'Nongsa, Batam',
    price: 8500000000,
    beds: 5,
    baths: 5,
    buildingArea: 400,
    landArea: 600,
    images: RUMAH_IMAGES,
    description: 'Villa pribadi mewah dengan akses langsung ke pantai pribadi di kawasan Nongsa.',
    features: ['Private Beach Access', 'Pemandangan Singapura', 'Kolam Renang Infinity', 'Sangat Pribadi'],
    coordinates: { lat: 1.17, lng: 104.12 },
  },
  {
    id: '41',
    title: 'Rumah Sederhana di Piayu',
    type: 'Rumah',
    location: 'Piayu, Batam',
    price: 400000000,
    beds: 2,
    baths: 1,
    buildingArea: 45,
    landArea: 78,
    images: RUMAH_IMAGES,
    description: 'Rumah di kawasan berkembang Piayu, dekat dengan area wisata laut.',
    features: ['Dekat Wisata Pantai', 'Harga Ekonomis', 'Kawasan Berkembang', 'Investasi Awal'],
    coordinates: { lat: 1.01, lng: 104.05 },
  },
  {
    id: '42',
    title: 'Tanah Industri di Kabil',
    type: 'Tanah Kosong',
    location: 'Kabil, Batam',
    price: 30000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 12000,
    images: TANAH_KOSONG_IMAGES,
    description: 'Lahan industri di kawasan terpadu Kabil, cocok untuk industri berat.',
    features: ['Kawasan Industri Terpadu', 'Akses Pelabuhan Kargo', 'Infrastruktur Lengkap', 'Zona Industri Berat'],
    coordinates: { lat: 1.09, lng: 104.12 },
  },
  {
    id: '43',
    title: 'Apartemen di Imperium',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 1800000000,
    beds: 2,
    baths: 2,
    buildingArea: 85,
    landArea: 85,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen eksklusif di The Imperium, Batam Center, dengan private lift.',
    features: ['Private Lift', 'Unit Terbatas', 'Pemandangan Kota', 'Dekat Kantor Pemerintahan'],
    coordinates: { lat: 1.122, lng: 104.045 },
  },
  {
    id: '44',
    title: 'Rumah di Perumahan Puri Legenda',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1100000000,
    beds: 3,
    baths: 2,
    buildingArea: 90,
    landArea: 98,
    images: RUMAH_IMAGES,
    description: 'Rumah di lokasi yang sangat strategis, Puri Legenda, dekat sekolah dan pasar.',
    features: ['Sangat Strategis', 'Dekat Sekolah Mondial', 'Pasar Puri Legenda', 'Akses Mudah'],
    coordinates: { lat: 1.108, lng: 104.061 },
  },
  {
    id: '45',
    title: 'Tanah Matang di Bengkong',
    type: 'Tanah Kosong',
    location: 'Bengkong, Batam',
    price: 2000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 500,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah matang siap bangun di kawasan padat penduduk Bengkong.',
    features: ['Tanah Matang', 'Padat Penduduk', 'Cocok untuk Kos-kosan', 'Dekat Golden Prawn'],
    coordinates: { lat: 1.148, lng: 104.03 },
  },
  {
    id: '46',
    title: 'Rumah Hook di Citra Indah',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 2000000000,
    beds: 3,
    baths: 3,
    buildingArea: 180,
    landArea: 210,
    images: RUMAH_IMAGES,
    description: 'Rumah hook di perumahan Citra Indah, seberang Mega Mall Batam Center.',
    features: ['Depan Mega Mall', 'Posisi Hook', 'Jalan Kaki ke Feri Terminal', 'Prime Location'],
    coordinates: { lat: 1.117, lng: 104.047 },
  },
  {
    id: '47',
    title: 'Apartemen Tipe Besar di The Hills',
    type: 'Apartemen',
    location: 'Sukajadi, Batam',
    price: 3800000000,
    beds: 3,
    baths: 3,
    buildingArea: 160,
    landArea: 160,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen tipe besar dengan pemandangan lapangan golf di The Hills, Sukajadi.',
    features: ['View Lapangan Golf', 'Unit Luas', 'Kawasan Elit', 'Udara Segar'],
    coordinates: { lat: 1.133, lng: 104.043 },
  },
  {
    id: '48',
    title: 'Tanah Pinggir Pantai di Batu Besar',
    type: 'Tanah Kosong',
    location: 'Batu Besar, Batam',
    price: 7000000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 8000,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah pinggir pantai di area Batu Besar, dekat bandara. Cocok untuk resort atau restoran seafood.',
    features: ['Pinggir Pantai', 'Dekat Bandara', 'Pemandangan Indah', 'Zona Pariwisata'],
    coordinates: { lat: 1.1, lng: 104.13 },
  },
  {
    id: '49',
    title: 'Rumah di Perumahan Cendana',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1700000000,
    beds: 3,
    baths: 2,
    buildingArea: 140,
    landArea: 150,
    images: RUMAH_IMAGES,
    description: 'Rumah terawat di Perumahan Cendana, salah satu perumahan favorit di Batam Center.',
    features: ['Lokasi Favorit', 'One Gate System', 'Lingkungan Aman', 'Dekat Sekolah Yos Sudarso'],
    coordinates: { lat: 1.129, lng: 104.053 },
  },
  {
    id: '50',
    title: 'Ruko di Komplek Windsor',
    type: 'Ruko',
    location: 'Nagoya, Batam',
    price: 2800000000,
    beds: 0,
    baths: 3,
    buildingArea: 200,
    landArea: 80,
    images: RUKO_IMAGES,
    description: 'Ruko di komplek Windsor yang ramai, pusat perdagangan dan perkantoran di Nagoya.',
    features: ['Pusat Perdagangan', 'Kawasan Ramai', 'Cocok untuk Kantor', 'Investasi Menarik'],
    coordinates: { lat: 1.144, lng: 104.016 },
  },
  {
    id: '51',
    title: 'Apartemen di The Summer',
    type: 'Apartemen',
    location: 'Batam Center, Batam',
    price: 700000000,
    beds: 1,
    baths: 1,
    buildingArea: 35,
    landArea: 35,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen kompak dengan fasilitas lengkap, dekat dengan Pasar Pasir Putih.',
    features: ['Fasilitas Lengkap', 'Dekat Pasar', 'Harga Kompetitif', 'Cocok untuk Pasangan Muda'],
    coordinates: { lat: 1.112, lng: 104.041 },
  },
  {
    id: '52',
    title: 'Rumah di Plamo Garden',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 1400000000,
    beds: 3,
    baths: 2,
    buildingArea: 118,
    landArea: 130,
    images: RUMAH_IMAGES,
    description: 'Rumah di Plamo Garden, perumahan dengan danau buatan dan lingkungan yang hijau.',
    features: ['Ada Danau Buatan', 'Lingkungan Hijau', 'Dekat Pollux Habibie', 'Row Jalan Lebar'],
    coordinates: { lat: 1.121, lng: 104.042 },
  },
  {
    id: '53',
    title: 'Tanah Kavling di Duriangkang',
    type: 'Tanah Kosong',
    location: 'Duriangkang, Batam',
    price: 500000000,
    beds: 0,
    baths: 0,
    buildingArea: 0,
    landArea: 300,
    images: TANAH_KOSONG_IMAGES,
    description: 'Tanah kavling di area yang sedang berkembang pesat di Duriangkang.',
    features: ['Area Berkembang', 'Investasi Tanah', 'Harga Masih Murah', 'Dekat Waduk Duriangkang'],
    coordinates: { lat: 1.04, lng: 104.06 },
  },
  {
    id: '54',
    title: 'Rumah Tua di Baloi',
    type: 'Rumah',
    location: 'Baloi, Batam',
    price: 1000000000,
    beds: 3,
    baths: 1,
    buildingArea: 120,
    landArea: 200,
    images: RUMAH_IMAGES,
    description: 'Rumah tua di kawasan Baloi yang sangat strategis, butuh renovasi total atau bangun ulang.',
    features: ['Lokasi Strategis Baloi', 'Hitung Tanah', 'Potensi Bangun Ulang', 'Dekat BCS Mall'],
    coordinates: { lat: 1.132, lng: 104.02 },
  },
  {
    id: '55',
    title: 'Apartemen Mewah di Aston',
    type: 'Apartemen',
    location: 'Nagoya, Batam',
    price: 2200000000,
    beds: 2,
    baths: 2,
    buildingArea: 90,
    landArea: 90,
    images: APARTEMEN_IMAGES,
    description: 'Apartemen mewah yang menyatu dengan Hotel Aston Nagoya, nikmati fasilitas hotel.',
    features: ['Menyatu dengan Hotel', 'Fasilitas Hotel', 'Disewakan Mudah', 'Lokasi Pusat Nagoya'],
    coordinates: { lat: 1.147, lng: 104.013 },
  },
  {
    id: '56',
    title: 'Rumah Cluster di Taman Raya',
    type: 'Rumah',
    location: 'Batam Center, Batam',
    price: 900000000,
    beds: 2,
    baths: 2,
    buildingArea: 70,
    landArea: 90,
    images: RUMAH_IMAGES,
    description: 'Rumah di perumahan besar Taman Raya, fasilitas sangat lengkap di dalam perumahan.',
    features: ['Perumahan Besar', 'Fasum Lengkap', 'Dekat Plaza Botania', 'Banyak Pilihan Kuliner'],
    coordinates: { lat: 1.114, lng: 104.075 },
  },
];

    